name: ETL Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy pytest python-dateutil

      - name: Run ETL unit tests
        run: |
          pytest src/tests/ --maxfail=1 --disable-warnings -q

      - name: Push cleaned data
        if: success()  # ← seulement si les tests passent
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          cp src/data/clean_students.csv ./data/
          git add data/clean_students.csv
          git commit -m "Add cleaned data [ci skip]"
          git push origin main
