name: ETL Unit Tests

on:
  push:
    branches:
      - raw-data
  workflow_dispatch:

jobs:
  test-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL unit tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Push clean data if tests pass
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -B clean-data
          python src/run_pipeline.py   # script qui génère data/clean_students.csv
          git add data/clean_students.csv
          git commit -m "Update clean data"
          git push -u origin clean-data --force
